### ISSUE TITLE
Output sound from the Alexa Skill

### ISSUE THREAD

**Issue by yasmeen789** [yasmeen789/Reading_Bot#1]

**Comment by yasmeen789** [comment]
Tried following the 'Super Simple Audio Player' code: https://github.com/bespoken/super-simple-audio-player

However appears with the following error: "The remote endpoint could not be called, or the response it returned was invalid" under 'Service Response'.

**Comment by yasmeen789** [comment]
Found a great tutorial explaining how to input SSML tags in JavaScript program. https://www.youtube.com/watch?v=atYubLO92u0. 

So far got up to 16.:44. Continue video from here where it will discuss how to input audio files into program.

**Comment by yasmeen789** [comment]
I added Sunil Syal's github code to my project, but it came out with the following errors when testing in Lambda:

Response:
{
  "errorMessage": "Cannot find module 'alexa-sdk'",
  "errorType": "Error",
  "stackTrace": [
    "Module.require (module.js:497:17)",
    "require (internal/module.js:20:19)",
    "Object.<anonymous> (/var/task/index.js:200:13)",
    "Module._compile (module.js:570:32)",
    "Object.Module._extensions..js (module.js:579:10)",
    "Module.load (module.js:487:32)",
    "tryModuleLoad (module.js:446:12)",
    "Function.Module._load (module.js:438:3)"
  ]
}

Request ID:
"38148236-0692-11e8-98d4-21a34f2d8fe8"

Function Logs:
START RequestId: 38148236-0692-11e8-98d4-21a34f2d8fe8 Version: $LATEST
Unable to import module 'index': Error
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/var/task/index.js:200:13)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
END RequestId: 38148236-0692-11e8-98d4-21a34f2d8fe8
REPORT RequestId: 38148236-0692-11e8-98d4-21a34f2d8fe8	Duration: 9.18 ms	Billed Duration: 100 ms 	Memory Size: 128 MB	Max Memory Used: 19 MB	

I also tried this tutorial before from scratch, and sent the author the following message: 
"Thanks so much for this tutorial, it is very helpful, except for one problem... I have tried several times to implement this skill, however every time I get the error: "The remote endpoint could not be called, or the response it returned was invalid.". This occurs at 11.20 of the video under service response. Do you have any idea what I am doing wrong? Thanks in advance."

He replied:
"It is very simple implementation and you should not get any error ideally. Can you exactly replicate the code and check? You can download the sample from the git - the link is available in the description section."

I had already tried these options so did not reply.

**Comment by yasmeen789** [comment]
So I have got the program to output text from an SSML tag using this tutorial: 
https://www.youtube.com/watch?v=atYubLO92u0

However it only works by being the first AND last thing to be outputted. This means it is repeated, and there is no place for the user to request the book. It starts playing the book at the beginning, and at the end.

However, I have put the lines into an array, which are called during a for loop.

**Comment by yasmeen789** [comment]
I have asked a question... however until I find a way to output SSML in the main body of the program, then I can't receive feedback. I have added changes to the branch audio and will continue working from a new branch.
